export const SET_APP_DATA = 'SET_APP_DATA';
export const ADD_APP_DATA = 'ADD_APP_DATA';
export const CHANGE_FLAG_APP_DATA = 'CHANGE_FLAG_APP_DATA';
export const SET_FLAGS_TRUE_APP_DATA = 'SET_FLAG_TRUE_APP_DATA';
